version: '3'
services: 
    app:
        build:
            args:
                user: tranquil
                uid: 1000
            context: ./build/app
            dockerfile: php.dockerfile
        image: tranquillity-core
        container_name: tranquillity-core-app
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - tranquillity

    db:
        image: mysql:8.0
        container_name: tranquillity-core-db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - ./build/db:/docker-entrypoint-initdb.d
        networks:
            - tranquillity

    web:
        image: nginx:latest
        container_name: tranquillity-core-web
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes: 
            - ./:/var/www
            - ./build/web/nginx.conf:/etc/nginx/conf.d/nginx.conf
        networks:
            - tranquillity
    
networks:
    tranquillity:
        driver: bridge